# config.yaml
program: train.py
method: random
name: waferfix-sweep
description: 3번째 시도, 하이퍼라마미터 최적화에서 pick
metric:
  goal: maximize
  name: test_best_f1
command:
  - ${env}
  - ${interpreter}
  - ${program}
  - "--project-name"
  - "waferfix-sweep"
  - "--gpus"
  - "0"
  - "--sweep"
  - "--wandb"
  - "--epochs"
  - "150"
  - "--arch"
  - "resnet18"
  - "--batch-size"
  - "256"
parameters:
  seed:  #1
    value: 1234 
  proportion: #2
    values: [0.1, 0.25, 0.5, 1.0]
  n_weaks_combinations:  #3
    values: [2, 3, 4, 5, 6]
  tau: #4 
    min: 0.3
    max: 0.5
  threshold:   #5
    min: 0.8
    max: 0.95
  lambda_u: #6
    min: 0.1
    max: 3.0 
  mu: #7
    distribution: int_uniform
    min: 3
    max: 7
  nm_optim:  #8
    values: ["adamw"]
  keep:   #9 
    values:
      - True
      - False
  limit_unlabled: # 638,507 (total)  #10
    values:
      - 300000 
      - 630000
  lr: #11
    values:
      - 0.01
  aug_types:  #12
    values: ["crop,cutout,noise,rotate,shift"]

early_terminate:
  type: hyperband
  min_iter: 70